return {
	{id="Add"          , size=16 , theme=nil     , content="rbxasset://hotswap_add_16.png"},
	{id="Add"          , size=32 , theme=nil     , content="rbxasset://hotswap_add_32.png"},
	{id="Changelog"    , size=16 , theme="Dark"  , content="rbxasset://hotswap_changelog_dark_16.png"},
	{id="Changelog"    , size=16 , theme="Light" , content="rbxasset://hotswap_changelog_light_16.png"},
	{id="Changelog"    , size=32 , theme="Dark"  , content="rbxasset://hotswap_changelog_dark_32.png"},
	{id="Changelog"    , size=32 , theme="Light" , content="rbxasset://hotswap_changelog_light_32.png"},
	{id="Disabled"     , size=16 , theme=nil     , content="rbxasset://hotswap_disabled_16.png"},
	{id="Disabled"     , size=32 , theme=nil     , content="rbxasset://hotswap_disabled_32.png"},
	{id="Enabled"      , size=16 , theme=nil     , content="rbxasset://hotswap_enabled_16.png"},
	{id="Enabled"      , size=32 , theme=nil     , content="rbxasset://hotswap_enabled_32.png"},
	{id="Help"         , size=16 , theme=nil     , content="rbxasset://hotswap_help_16.png"},
	{id="Help"         , size=32 , theme=nil     , content="rbxasset://hotswap_help_32.png"},
	{id="Logo"         , size=16 , theme=nil     , content="rbxasset://hotswap_logo_16.png"},
	{id="Logo"         , size=32 , theme=nil     , content="rbxasset://hotswap_logo_32.png"},
	{id="Remove"       , size=16 , theme=nil     , content="rbxasset://hotswap_remove_16.png"},
	{id="Remove"       , size=32 , theme=nil     , content="rbxasset://hotswap_remove_32.png"},
	{id="RemoveAll"    , size=16 , theme="Dark"  , content="rbxasset://hotswap_removeall_dark_16.png"},
	{id="RemoveAll"    , size=16 , theme="Light" , content="rbxasset://hotswap_removeall_light_16.png"},
	{id="RemoveAll"    , size=32 , theme="Dark"  , content="rbxasset://hotswap_removeall_dark_32.png"},
	{id="RemoveAll"    , size=32 , theme="Light" , content="rbxasset://hotswap_removeall_light_32.png"},
	{id="ScrollBottom" , size=16 , theme=nil     , content="rbxasset://hotswap_scroll_bottom_16.png"},
	{id="ScrollBottom" , size=32 , theme=nil     , content="rbxasset://hotswap_scroll_bottom_32.png"},
	{id="ScrollMiddle" , size=16 , theme=nil     , content="rbxasset://hotswap_scroll_middle_16.png"},
	{id="ScrollMiddle" , size=32 , theme=nil     , content="rbxasset://hotswap_scroll_middle_32.png"},
	{id="ScrollTop"    , size=16 , theme=nil     , content="rbxasset://hotswap_scroll_top_16.png"},
	{id="ScrollTop"    , size=32 , theme=nil     , content="rbxasset://hotswap_scroll_top_32.png"},
}
